### ISSUE TITLE
Bootstrapping

### ISSUE THREAD

**Issue by phoe** [wadehennessey/wcl#2]
Is it possible to bootstrap this off another Common Lisp implementation or compile it from pure source code? I see that you have a WCL binary in your source tree; is it required?

**Comment by wadehennessey** [comment]
Wcl used to be cross compiled when I first wrote it 26 years ago, but that stopped in about 1992 when wcl started recompiling itself and cross compilation support was dropped. You need to use the binary that's in the tree do that now, so yes, it's required. 

The way I usually do that is to cd to wcl/src/build and run ./compile-all. That will use the wcl/dist-bin and wcl/dist-lib binaries to compile a new version of wcl that will show up in wcl/bin and wcl/lib. Let me know if you have a problem.

**Comment by wadehennessey** [comment]
I've reverted git repository to the original gc in wcl, so there are no rtgc dependencies.

If you want real-time gc support uncomment this line in wcl/src/cl/c-src/lisp.h:

//#define RTGC 1

You'll have to change any hardwired references to /home/wade to suit your situation though.
